export const navigation = [
  {
    title: 'Introduction',
    links: [
      { title: 'Why Funtypes?', href: '/' },
      { title: 'Getting started', href: '/docs/getting-started' },
    ],
  },
  {
    title: 'Main API',
    links: [
      { title: 'Codec', href: '/docs/funtypes-api-codec' },
      { title: 'Codec.test', href: '/docs/funtypes-api-test' },
      { title: 'Codec.parse', href: '/docs/funtypes-api-parse' },
      { title: 'Codec.safeParse', href: '/docs/funtypes-api-safeparse' },
      { title: 'Codec.serialize', href: '/docs/funtypes-api-serialize' },
      { title: 'Codec.safeSerialize', href: '/docs/funtypes-api-safeserialize' },
      { title: 'Codec.withConstraint & Codec.withGuard', href: '/docs/funtypes-api-withconstraint' },
      { title: 'Codec.withParser', href: '/docs/funtypes-api-withparser' },
      { title: 'Codec.introspection', href: '/docs/funtypes-api-introspection' },
      { title: 'Result', href: '/docs/funtypes-api-result' },
      { title: 'ValidationError', href: '/docs/funtypes-api-validation-error' },
    ],
  },
  {
    title: 'Built In Types',
    links: [
      { title: 'Array', href: '/docs/types-array' },
      { title: 'Constraint & Guard', href: '/docs/types-constraint' },
      { title: 'Enum', href: '/docs/types-enum' },
      { title: 'InstanceOf', href: '/docs/types-instanceof' },
      { title: 'Intersect', href: '/docs/types-intersect' },
      { title: 'KeyOf', href: '/docs/types-keyof' },
      { title: 'Lazy', href: '/docs/types-lazy' },
      { title: 'Literal', href: '/docs/types-literal' },
      { title: 'Mutable', href: '/docs/types-mutable' },
      { title: 'Named', href: '/docs/types-named' },
      { title: 'Never', href: '/docs/types-never' },
      { title: 'Object', href: '/docs/types-object' },
      { title: 'Omit', href: '/docs/types-omit' },
      { title: 'ParsedValue', href: '/docs/types-parsed-value' },
      { title: 'Partial', href: '/docs/types-partial' },
      { title: 'Pick', href: '/docs/types-pick' },
      { title: 'Primitive', href: '/docs/types-primitive' },
      { title: 'Readonly', href: '/docs/types-readonly' },
      { title: 'Record', href: '/docs/types-record' },
      { title: 'Sealed', href: '/docs/types-sealed' },
      { title: 'Tuple', href: '/docs/types-tuple' },
      { title: 'Union', href: '/docs/types-union' },
      { title: 'Unknown', href: '/docs/types-unknown' },
      { title: 'WithComment', href: '/docs/types-with-comment' },
      { title: 'WithDefault', href: '/docs/types-with-default' },
    ],
  },
  {
    title: 'Utilities',
    links: [
      { title: 'assertType', href: '/docs/funtypes-api-asserttype' },
      { title: 'showError', href: '/docs/funtypes-api-showerror' },
      { title: 'showType', href: '/docs/funtypes-api-showtype' },
      { title: 'showValue', href: '/docs/funtypes-api-showvalue' },
    ],
  },
  {
    title: 'Ecosystem',
    links: [
      { title: 'Standard Schema & JSON Schema', href: '/docs/standard-schema' },
    ],
  },
]
